#import "VisibilityViewController.h"
#import "IMAssetApi.h"
#import "AssetGridViewController.h"
#import "common.h"
@interface VisibilityViewController ()
@property(nonatomic,copy) NSString *visibility; @property(nonatomic,strong) UILabel *status; @property(nonatomic,strong) UIActivityIndicatorView *spinner; @property(nonatomic,strong) NSArray<IMAsset *> *assets;
@property(nonatomic) BOOL hasPresentedGrid;
@end
@implementation VisibilityViewController
- (instancetype)initWithVisibility:(NSString *)visibility title:(NSString *)title { if((self=[super init])){_visibility=[visibility copy]; self.title=title; _assets=@[];} return self; }
- (void)viewDidLoad { [super viewDidLoad]; self.view.backgroundColor=UIColor.systemBackgroundColor; self.status=[[UILabel alloc]init]; self.status.translatesAutoresizingMaskIntoConstraints=NO; self.status.textAlignment=NSTextAlignmentCenter; self.status.numberOfLines=0; self.spinner=[[UIActivityIndicatorView alloc]initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium]; self.spinner.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:self.status]; [self.view addSubview:self.spinner]; [NSLayoutConstraint activateConstraints:@[[self.status.centerXAnchor constraintEqualToAnchor:self.view.centerXAnchor],[self.status.centerYAnchor constraintEqualToAnchor:self.view.centerYAnchor constant:-20],[self.status.leadingAnchor constraintGreaterThanOrEqualToAnchor:self.view.leadingAnchor constant:24],[self.status.trailingAnchor constraintLessThanOrEqualToAnchor:self.view.trailingAnchor constant:-24],[self.spinner.centerXAnchor constraintEqualToAnchor:self.view.centerXAnchor],[self.spinner.topAnchor constraintEqualToAnchor:self.status.bottomAnchor constant:16]]]; self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(reload)]; [self reload]; }
- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; [self reload]; }
- (void)reload { [self.spinner startAnimating]; __weak typeof(self) w=self; [IMAssetApi timeBucketsWithVisibility:self.visibility completion:^(NSArray<NSString *> *dates,NSArray<NSNumber *> *counts,NSError *e){ if(e||!dates.count){dispatch_async(dispatch_get_main_queue(),^{[w.spinner stopAnimating];w.status.text=e?_(@"Unable to load photos."):_(@"No photos");if(e)[w showError:e];});return;} dispatch_group_t g=dispatch_group_create();NSMutableArray *all=[NSMutableArray array];__block NSError *first;for(NSString*d in dates){dispatch_group_enter(g);[IMAssetApi assetsInTimeBucket:d visibility:w.visibility completion:^(NSArray<IMAsset*>*a,NSError*err){if(err)first=err;else @synchronized(all){[all addObjectsFromArray:a?:@[]];}dispatch_group_leave(g);}];}dispatch_group_notify(g,dispatch_get_main_queue(),^{[w.spinner stopAnimating];w.assets=all;w.status.text=[NSString stringWithFormat:_(@"%ld photos"),(long)all.count];if(first)[w showError:first];if(all.count&&!w.hasPresentedGrid){w.hasPresentedGrid=YES;[w.navigationController pushViewController:[AssetGridViewController gridWithTitle:w.title assets:all] animated:YES];}}); }]; }
- (void)showError:(NSError*)e { UIAlertController*a=[UIAlertController alertControllerWithTitle:self.title message:e.localizedDescription?:_(@"Request failed") preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:_(@"OK") style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil]; }
@end
